name: Scrape Barchart Top 100

on:
  schedule:
    - cron: '0 12 * * *'  # Runs every day at 12:00 UTC
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          playwright install --with-deps

#      - name: Run scraper
#        run: python barchart_scraper.py
      - name: Run scraper with debug output
        run: |
          python barchart_scraper.py || (echo "❌ Script failed" && exit 1)

      - name: Upload CSV artifact
        uses: actions/upload-artifact@v4
        with:
          name: top-100-stocks
          path: top_100_stocks.csv

      - name: Upload debug HTML if exists
        if: always()
        run: |
          if [ -f debug_page.html ]; then
            echo "Uploading debug_page.html"
          else
            echo "No debug_page.html to upload"
          fi
        continue-on-error: true

      - name: Upload debug_page.html artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: debug-page
          path: debug_page.html
